# Generated by Django 2.1.7 on 2021-06-11 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210611_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 11, 12, 26, 37, 463286)),
        ),
    ]
